title: Rahul
author: rahulpk94
email: rahulpkumar3g@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Google LLC is an American multinational technology company that 
  specializes in Internet-related services and products, which include 
  online advertising technologies, search engine, cloud computing, 
  software, and hardware. It is considered one of the Big Four technology companies, 
  alongside Amazon, Apple and Facebook. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
